export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
export const SEARCH_ERROR = "SEARCH_ERROR";
export const SEARCH_PENDING = "SEARCH_PENDING";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const ADD_TO_MY_CONTENT = "ADD_TO_MY_CONTENT";
export const ADD_TO_MY_WATCHED = "ADD_TO_MY_WATCHED";
export const REMOVE_FROM_MY_CONTENT = "REMOVE_FROM_MY_CONTENT";
